### ISSUE TITLE
Improve consistency of tmctl brokers command, expecting e.g. tmctl list brokers

### ISSUE THREAD

**Issue by jmcx** [triggermesh/tmctl#113]
Based on multiple people's feedback during our mini hackathon today

**Comment by sebgoa** [comment]
if we follow `kubectl` we could have a `get` command -not a `list` and have:

* get brokers
* get sources
* get targets

so that we can see them as a list per type and potentially get a single one.

It does feel a bit redundant compared to `describe`

**Comment by jmcx** [comment]
Closing for now as we haven't converged on anything.
