### ISSUE TITLE
tmctl send-event should clarify it only expects json

### ISSUE THREAD

**Issue by jmcx** [triggermesh/tmctl#114]
from pablo during hackathon today

if you pass a simple string like "hello" the broker just gets an empty string.

solution idea: enforce that send-event should on accept json. 
alternative: if it can, it could transform a simple string to JSON by adding a key like {"triggermesh says":"...."}.

**Comment by tzununbekov** [comment]
Addressed in https://github.com/triggermesh/tmctl/issues/108#issuecomment-1326052712
