### ISSUE TITLE
rename "azureeventhub" to "azureeventhubs" in list of sources

### ISSUE THREAD

**Issue by jmcx** [triggermesh/tmctl#115]
we should consistently have hubs plural across the board.

related issue for tm/tm: https://zube.io/triggermesh/triggermesh/c/9732 

FYI the target uses plural as it should.

**Comment by tzununbekov** [comment]
This first should be fixed upstream since CLI pulls resources data from the triggermesh/triggermesh release CRDs

**Comment by odacremolbap** [comment]
Yep, this should be the case once next tm/tm is released https://github.com/triggermesh/triggermesh/pull/1225
