### ISSUE TITLE
Improve send-event logging output

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/tmctl#119]
```
$ tmctl send-event --eventType io.foo.com "foobar"
foobar -> http://localhost:60993
OK'
```

**Comment by tzununbekov** [comment]
Output improved.
<img width="585" alt="Screenshot 2022-11-24 at 11 22 51 AM" src="https://user-images.githubusercontent.com/13515865/203700841-450a12f0-362a-472a-af93-95dd3c170f5d.png">

**Comment by sebgoa** [comment]
nice, thanks
