### ISSUE TITLE
Autocompletion not loading automatically on ZSH mac

### ISSUE THREAD

**Issue by jmcx** [triggermesh/tmctl#155]
I installed https://github.com/marlonrichert/zsh-autocomplete. 

Then ran these commands which were in the previous version of the quickstart: 

```
source <(tmctl completion zsh)
compdef _tmctl tmctl
```

And managed to get autocomplete working. 

Also ran 

`tmctl completion zsh > $(brew --prefix)/share/zsh/site-functions/_tmctl`

But when I create a new terminal window autocompletion is not working. 

If I re-run

```
source <(tmctl completion zsh)
~ % compdef _tmctl tmctl
```

then it works again in the new terminal.

**Comment by jmcx** [comment]
Upon some further exploration, the two initial commands will work so long as you either add `autoload -U +X compinit && compinit` to you .zshrc OR install something like https://github.com/marlonrichert/zsh-autocomplete.

**Comment by tzununbekov** [comment]
I believe that simply following the completion command `--help` output would solve the problem. We could put this recommendation in the docs, or follow kubectl's [example](https://kubernetes.io/docs/tasks/tools/included/).

```
tmctl@docs$ tmctl completion zsh --help
Generate the autocompletion script for the zsh shell.

If shell completion is not already enabled in your environment you will need
to enable it.  You can execute the following once:

	echo "autoload -U compinit; compinit" >> ~/.zshrc

To load completions in your current shell session:

	source <(tmctl completion zsh); compdef _tmctl tmctl

To load completions for every new session, execute once:

#### Linux:

	tmctl completion zsh > "${fpath[1]}/_tmctl"

#### macOS:

	tmctl completion zsh > $(brew --prefix)/share/zsh/site-functions/_tmctl

You will need to start a new shell for this setup to take effect.

Usage:
  tmctl completion zsh [flags]

Flags:
  -h, --help              help for zsh
      --no-descriptions   disable completion descriptions

Global Flags:
      --broker string    Optional broker name.
      --version string   TriggerMesh components version.
```

**Comment by jmcx** [comment]
Proposing new instructions for ZSH here: https://github.com/triggermesh/docs/commit/dd55d95c173ce8bf5e3621c875f8a3ee6052c0ca that seem reliable, closing this issue for now (also there is still a another issue with autocomplete not working out of the box with brew).
