### ISSUE TITLE
Azure Event Hubs source does not work

### ISSUE THREAD

**Issue by cparlette** [triggermesh/tmctl#185]
❯ tmctl create source azureeventhub --eventHubID "redacted" --auth.servicePrincipal.tenantID redacted --auth.servicePrincipal.clientID redacted --auth.servicePrincipal.clientSecret redacted
2022/12/12 15:29:28 foo | Updating manifest
Usage:
  tmctl create source [kind]/[--from-image <image>][--name <name>] [flags]

Examples:
tmctl create source httppoller \
	--endpoint https://www.example.com \
	--eventType sample-event \
	--interval 30s  \
	--method GET

Flags:
  -h, --help   help for source

Global Flags:
      --broker string    Optional broker name.
      --version string   TriggerMesh components version.

2022/12/12 15:29:28 source initialization: CRD schema not found: CRD for resource "azureeventhubsource" does not exist

**Comment by tzununbekov** [comment]
Related to #115
