### ISSUE TITLE
Azure Blob Storage source does not work

### ISSUE THREAD

**Issue by cparlette** [triggermesh/tmctl#186]
❯ tmctl create source azureblobstorage --storageAccountID redacted --endpoint.eventHubs.namespaceID redacted --auth.servicePrincipal.tenantID redacted --auth.servicePrincipal.clientID redacted --auth.servicePrincipal.clientSecret redacted
2022/12/12 15:27:27 foo | Updating manifest
2022/12/12 15:27:33 foo | Starting container
Usage:
  tmctl create source [kind]/[--from-image <image>][--name <name>] [flags]

Examples:
tmctl create source httppoller \
	--endpoint https://www.example.com \
	--eventType sample-event \
	--interval 30s  \
	--method GET

Flags:
  -h, --help   help for source

Global Flags:
      --broker string    Optional broker name.
      --version string   TriggerMesh components version.

2022/12/12 15:27:34 pulling image: Error response from daemon: manifest for gcr.io/triggermesh/azureeventhubsource-adapter:v1.22.0 not found: manifest unknown: Failed to fetch "v1.22.0" from request "/v2/triggermesh/azureeventhubsource-adapter/manifests/v1.22.0".

**Comment by tzununbekov** [comment]
Related to #115
