### ISSUE TITLE
tmctl watch not working on windows

### ISSUE THREAD

**Issue by jeffreywstevens** [triggermesh/tmctl#254]
It appears like the "tmctl send-event" command is not populating the ID field. I am assuming that is why the corresponding watch windows it not receiving the events.  Is this the problem?

<img width="491" alt="image" src="https://user-images.githubusercontent.com/637945/219527170-7f4a5f49-9689-427b-beb0-f87a389dc8e9.png">

**Comment by tzununbekov** [comment]
Missing ID in the command output should not be the issue - the HTTP client populates the CE timestamp and ID. One of the possible causes can be the Docker configuration - `send-event` command sends the events to the `http://localhost:<port>`, expecting the TriggerMesh containers to run on the same host machine. If Docker is configured with the remote host or some other network configurations, where containers are unavailable on the localhost, events would not make it to the `watch` output. The screenshot suggests that you are on Windows, right? What about Docker configuration, is it the default setup with the containers on the same host machine? If you are on the latest tmctl, what `tmctl logs` show?

**Comment by jeffreywstevens** [comment]
I think I opened another command prompt to tail the logs and it didn't show anything.  Just for clarification, how should I display the tmctl logs?

I also wrote my own app to publish cloudevents to the localhost endpoint in docker. It published just fine to the endpoint so I don't think networking is the issue. Still no output. That is where I left it yesterday.

**Comment by JeffNeff** [comment]
Do you have the WSL backend enabled for docker? I just tried testing on windows with the latest release and was not able to re-produce the problem.. 

![tmctl](https://user-images.githubusercontent.com/60796676/219706052-4b19fbf6-f817-4907-865d-c39d8b7500bc.PNG)

**Comment by JeffNeff** [comment]
please try with CMD instead of Powershell.

**Comment by jeffreywstevens** [comment]
Anyway, the good thing is that this forced me to setup Docker on my M1 MacBook.  It worked there!  I had to use brew for both.

So I will go back to the Windows boxes and see if I can figure it out. I have 3 more Windows boxes to try as well.

**Comment by jeffreywstevens** [comment]
Works on Mac, not on Windows.
<img width="560" alt="image" src="https://user-images.githubusercontent.com/637945/219878864-c8bb7489-f40b-48fd-ab80-714512edce5d.png">

**Comment by jeffreywstevens** [comment]
I am blocked because it prevents a quick and easy demonstration to my team. Plus, they are all on Windows. So far, 3 Windows machines, two personal, and one work, all don't work. I can try some VM dev boxes. I haven't looked at this in a couple of weeks but I want to put this in the R&D backlog for our K8s cluster.

**Comment by jmcx** [comment]
Thanks Jeffrey. Apologies if you already shared this: what versions of windows and what docker provider are you using?

**Comment by jmcx** [comment]
We reproduced on windows 10 with both CMD and Powershell.

**Comment by FranBarrera** [comment]
Hey @jeffreywstevens Can you try to restart the broker container with docker desktop or docker CLI (docker restart <broker_name>) the name of the container should be brokername-broker.

I've tested and it seems to works fine, these are my steps:

**powershell 1:**
```
tmctl create broker foo
```
**powershell 2:**
```
tmctl watch
```

**powershell 1:**
```
docker restart foo-broker
tmctl send event '{"foo":"bar"}'
```
And you will see the messages in the tmctl watch

**Comment by jeffreywstevens** [comment]
Excellent. That’s a good work around.

**Comment by tzununbekov** [comment]
Hey, we have a fix for this bug being prepared for merge today:
https://github.com/triggermesh/tmctl/pull/276

@jeffreywstevens thanks a lot for reporting the issue 🙏

**Comment by jmcx** [comment]
Thanks for releasing this fix @tzununbekov 🙇 

@jeffreywstevens tmctl patch version 1.2.1 was released earlier today. You can now update tmctl (see [instructions here](https://docs.triggermesh.io/latest/installation/how-to-update/#updating-tmctl)). You should also restart any running brokers on your machine, by doing `tmctl stop` then `tmctl start`. 

Hopefully this should do the trick. Please let us know how it goes! And apologies for this issue.

**Comment by jeffreywstevens** [comment]
It worked for me today after I cloned the repo and built the exe. We are good. Thanks for your help on this!

**Comment by jmcx** [comment]
Great to hear, let us know us you go!
