### ISSUE TITLE
Put the cli in brew

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/tmctl#35]
so that we can do 

```
brew install tmcli
```

**Comment by sameersbn** [comment]
tmctl needs to reach a certain number of stars/forks on the github repo to meet the acceptance criteria of the brew core library. Until then users will need to install tmctl using the tap https://github.com/triggermesh/homebrew-cli. To be precise the command to install would be:

```
brew install triggermesh/cli/tmctl
``` 

PR on docs https://github.com/triggermesh/docs/pull/317
PR on tmctl https://github.com/triggermesh/tmctl/pull/156
