### ISSUE TITLE
Proposal for Transformations in the CLI

### ISSUE THREAD

**Issue by jmcx** [triggermesh/tmctl#58]
This is a proposal for how Transformation could fit into the CLI, in a way that simplifies usage by the end user by not having to handle routing to and from the Transformation. It's inspired by EventBridge in that the Transformation is associated with a Target. 

A Transformation is associated with exactly one Target, and a Target has at most one Transformation. The Transformation must transform the event before it gets sent to the external consumer (no implication here on the actual event flow).

In the CLI, after creating a Target, you can add a transformation to that Target:

```
tmcli create target cloudevents --name mycetarget --endpoint https://sockeye-tzununbekov.dev.triggermesh.io/
tmcli create trigger --name mytrigger --source aws-s3 --target mycetarget
tmcli create transformation --target mycetarget --from-file bumblebee.txt
```

Functions would also be used in the same way

```
tmcli create target cloudevents --name mycetarget --endpoint https://sockeye-tzununbekov.dev.triggermesh.io/
tmcli create trigger --name mytrigger --source aws-s3 --target mycetarget
tmcli create function --target mycetarget --from-file myfunction.py
```

**Under the hood**

When mapped to the Kubernetes object model, this produces a multi-legged flow:
1. Trigger from Broker to Transformation
2. Transformation responds to Broker
3. Trigger from Broker to the CloudEvents Target

Alternatively it could also be a simple linear chain: Trigger from Broker to Transformation => Sink from Transformation to Target

**Implications/thoughts**

Later we could expand to add transformations to sources. One use case for this could be to improve the metadata of an incoming event in order to simplify routing and processing further down. For example, if I'm getting generic events of type aws.sqs.message from an SQS source, but I know that there are several message types in there and want to extract the type and update the ce type header. 
```
tmcli create transformation --source mysqssource --from-file bumblebee.txt
```

**Alternative designs**
- (currently in CLI) Transformation is a sink for a Trigger, that responds back to the Broker, and whose output event needs to be routed to another Target using a Trigger
- Transformation associated to a Trigger instead of a Target

**Comment by sebgoa** [comment]
closing this because we have transformation in the release
