### ISSUE TITLE
:Feature Request: Deploy Arbitrary Container Images as Services

### ISSUE THREAD

**Issue by JeffNeff** [triggermesh/tmctl#63]
I would like to be able to deploy arbitrary container images as services and define the respective environment variables and port mappings. I.E.

```
tmcli create service foo --env=["bob":"isnice","tom":"isnot"] --port=[8080:8080,50001:5001]
```
OR
```
tmcli create service --config=./config.json
```
WHERE `config.json` ==
```
{
name : foo,
env:
 [
  bob: isnice,
  tom: isnot,
],
port:
  [
   8080:8080,
   50001:5000
   ]
 }
```

**Comment by jmcx** [comment]
Is it fair to say we now have a V1 of this with the --from-image command? e.g.:

tmctl create target --from-image gcr.io/triggermesh/triggermesh-console:v0.0.1

If so maybe we can close this one for now?

**Comment by sebgoa** [comment]
closing this because we do have `--from-image`
