### ISSUE TITLE
Show fired Triggers with watch command

### ISSUE THREAD

**Issue by jmcx** [triggermesh/tmctl#86]
As a user, when I send an event into TriggerMesh and I want to debug to understand what is going on, there are two big questions: 
1) Did my event make it into the Broker, and what does it look like? 
2) Did my event match any Triggers, thereby resulting in it getting sent somewhere?

Today watch supports 1. but not 2. 

If I see my event in the Broker but I'm not getting the result I expected in an external target, my next question is: is it because the Trigger didn't fire, or is it because my external service didn't correctly consume the message? 

By showing which Triggers fired, it narrows down the error space to being something to do with the interaction between target and external consumer. It helps me validate if the Trigger filter correctly matched the event or not. 

**UX brainstorm**
```
% tmctl watch
2022/10/19 14:57:26 Watching...
☁️  cloudevents.Event
Context Attributes,
  specversion: 1.0
  type: my.custom.type
  source: my.custom.source
  id: A234-1234-1234
  time: 2019-10-12T07:20:50.52Z
Data,
   "{\"name\":\"toto\"}"

🔫  Trigger fired
Trigger Attributes,
  name: my-trigger
  filters: {"type"="my-type", "source"="my-source"}
  time: 2019-10-12T07:20:50.53Z
```

**Comment by NikhilSharmaWe** [comment]
@jmcx I am not very sure about how to add this to the `tmctl watch`.

I am thinking like in `tmctl describe`: https://github.com/triggermesh/tmctl/blob/main/cmd/describe/describe.go#L113

We can loop over all the triggers when func [listenEvents](https://github.com/triggermesh/tmctl/blob/main/cmd/watch/watch.go#L112) is executed and log for those triggers that match with the event.

I am not very sure about this, please inform if you have a better approach to implement this.

**Comment by jmcx** [comment]
Hi @NikhilSharmaWe, indeed this may not be immediately solvable (also based on what I've heard from the team). Solving it might require adding new telemetry to the broker, or similar. We have started some design work on a console that could show this sort of info, so I suggest we close this issue in favour of the console approach, which is a work in progress but hasn't left the design stage yet.
